# Generated by Django 4.0.4 on 2022-04-14 13:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='datecreate',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 4, 14, 13, 50, 28, 382141, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='dateupdate',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 4, 14, 13, 50, 28, 382167, tzinfo=utc)),
        ),
    ]
